# Generated by Django 2.2.15 on 2020-08-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_auto_20200824_1647'),
        ('album', '0002_auto_20200822_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(to='artist.Artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tag.Tag'),
        ),
        migrations.AlterField(
            model_name='album',
            name='tracks',
            field=models.ManyToManyField(blank=True, to='track.Track'),
        ),
    ]
