# Generated by Django 3.1.1 on 2020-10-11 14:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20201011_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artwork',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, null=True, size=None),
        ),
    ]
