# Generated by Django 3.1.1 on 2020-10-20 11:20

import album.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_auto_20201011_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artwork',
        ),
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=album.models.get_cover_path),
        ),
    ]
