# Generated by Django 3.1.2 on 2020-10-06 19:16

import uuid

from django.db import migrations, models

import artist.models
import upload.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_picture', models.FileField(storage=upload.storage_backends.PublicStorage(), upload_to=artist.models.get_profile_picture_path)),
                ('location', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=150, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=150, null=True)),
                ('bandcamp_link', models.CharField(blank=True, max_length=150, null=True)),
                ('soundcloud_link', models.CharField(blank=True, max_length=150, null=True)),
                ('beatport_link', models.CharField(blank=True, max_length=150, null=True)),
                ('albums', models.ManyToManyField(blank=True, to='album.Album')),
            ],
        ),
    ]
