# Generated by Django 3.1.1 on 2020-10-03 15:19

import artist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_auto_20200925_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile_picture',
            field=models.FileField(upload_to=artist.models.get_profile_picture_path),
        ),
    ]
