# Generated by Django 2.2.15 on 2020-08-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_remove_album_artists'),
        ('artist', '0003_auto_20200824_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='albums',
            field=models.ManyToManyField(to='album.Album'),
        ),
    ]
