# Generated by Django 3.1.1 on 2020-10-03 16:08

import artist.models
from django.db import migrations, models
import upload.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_auto_20201003_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile_picture',
            field=models.FileField(storage=upload.storage_backends.PublicStorage(), upload_to=artist.models.get_profile_picture_path),
        ),
    ]
