# Generated by Django 3.1.1 on 2020-10-03 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_auto_20200925_1952'),
        ('label', '0002_auto_20201003_1358'),
        ('user', '0002_auto_20200925_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='artist_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='artist.artist'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='label_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='label.label'),
        ),
    ]
