# Generated by Django 3.1.2 on 2020-10-06 19:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('picture', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('total_listens', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
