# Generated by Django 3.1.1 on 2020-10-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='total_listens',
            field=models.IntegerField(default=0),
        ),
    ]
