# Generated by Django 3.1.1 on 2020-10-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_auto_20201007_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='track',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='picture',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
