# Generated by Django 3.1.1 on 2020-10-12 13:20

from django.db import migrations, models

import track.models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_auto_20201011_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='file',
            field=models.FileField(max_length=150, upload_to=track.models.get_track_path),
        ),
    ]
