# Generated by Django 3.1.1 on 2020-10-12 13:26

from django.db import migrations, models

import track.models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0005_auto_20201012_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='file',
            field=models.FileField(max_length=255, upload_to=track.models.get_track_path),
        ),
    ]
