# Generated by Django 3.1.1 on 2020-10-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_auto_20201006_1916'),
        ('track', '0006_auto_20201012_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='artists',
            field=models.ManyToManyField(blank=True, to='artist.Artist'),
        ),
    ]
