# Generated by Django 3.1.1 on 2020-10-13 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0007_track_artists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='cost',
            new_name='price',
        ),
    ]
