# Generated by Django 3.1.1 on 2020-10-20 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0008_auto_20201013_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='location',
        ),
        migrations.RemoveField(
            model_name='track',
            name='picture',
        ),
    ]
