# Generated by Django 3.1.2 on 2020-10-06 19:16

import uuid

import django.contrib.postgres.fields
from django.db import migrations, models

import label.models
import upload.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0001_initial'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, null=True, size=None)),
                ('subscription_cost', models.IntegerField(null=True)),
                ('profile_picture', models.FileField(storage=upload.storage_backends.PublicStorage(), upload_to=label.models.get_profile_picture_path)),
                ('location', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=150, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=150, null=True)),
                ('bandcamp_link', models.CharField(blank=True, max_length=150, null=True)),
                ('soundcloud_link', models.CharField(blank=True, max_length=150, null=True)),
                ('beatport_link', models.CharField(blank=True, max_length=150, null=True)),
                ('artists', models.ManyToManyField(blank=True, to='artist.Artist')),
                ('tags', models.ManyToManyField(blank=True, to='tag.Tag')),
            ],
        ),
    ]
