# Generated by Django 3.1.1 on 2020-10-03 13:58

from django.db import migrations, models
import label.models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='profile_picture',
            field=models.FileField(upload_to=label.models.get_profile_picture_path),
        ),
    ]
