# Generated by Django 3.1.1 on 2020-10-03 15:19

from django.db import migrations, models
import label.models
import upload.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0002_auto_20201003_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='profile_picture',
            field=models.FileField(storage=upload.storage_backends.PublicStorage(), upload_to=label.models.get_profile_picture_path),
        ),
    ]
